services:
  - type: web
    name: libretranslate
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: LT_LOAD_ONLY
        value: en,fr,es,de,ar
